- name: This is main playbook for assignment 2
  hosts: linux
  pre_tasks:
   - debug:
        msg: "Beginning pre deployment activities"
  roles:
    - datadisk
    - system_profile
    - users
    - webserver
  post_tasks: 
   - debug:
        msg: "Successfully completed vm deployment"
